In [3]:
import numpy as np

# 1. Create an array
arr = np.array([1, 2, 3, 4, 5])

# 2. Get the shape of an array
shape = arr.shape

# 3. Reshape an array
#reshaped = arr.reshape(2, 3)

# 4. Generate an array of zeros
zeros = np.zeros((2, 3))

# 5. Generate an array of ones
ones = np.ones((3, 4))

# 6. Generate an identity matrix
identity = np.eye(3)

# 7. Create a range of values
range_arr = np.arange(1, 10, 2)

# 8. Create a linspace (linearly spaced) array
linspace_arr = np.linspace(0, 1, 5)

# 9. Perform element-wise addition
addition = np.add(arr, 5)

# 10. Perform element-wise subtraction
subtraction = np.subtract(arr, 2)

# 11. Perform element-wise multiplication
multiplication = np.multiply(arr, 3)

# 12. Perform element-wise division
division = np.divide(arr, 2)

# 13. Dot product of two arrays
dot_product = np.dot(arr, range_arr)

# 14. Transpose an array
transposed = arr.T

# 15. Find the maximum value in an array
max_value = arr.max()

# 16. Find the minimum value in an array
min_value = arr.min()

# 17. Sum of all elements in an array
array_sum = arr.sum()

# 18. Mean of all elements in an array
array_mean = arr.mean()

# 19. Standard deviation of elements in an array
std_deviation = arr.std()

# 20. Index of the maximum value
max_index = arr.argmax()

print("Original array:", arr)
print("Shape:", shape)
#print("Reshaped:", reshaped)
print("Zeros array:", zeros)
print("Ones array:", ones)
print("Identity matrix:", identity)
print("Range array:", range_arr)
print("Linspace array:", linspace_arr)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Dot product:", dot_product)
print("Transposed:", transposed)
print("Max value:", max_value)
print("Min value:", min_value)
print("Sum:", array_sum)
print("Mean:", array_mean)
print("Standard Deviation:", std_deviation)
print("Index of max value:", max_index)


Original array: [1 2 3 4 5]
Shape: (5,)
Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range array: [1 3 5 7 9]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Addition: [ 6  7  8  9 10]
Subtraction: [-1  0  1  2  3]
Multiplication: [ 3  6  9 12 15]
Division: [0.5 1.  1.5 2.  2.5]
Dot product: 95
Transposed: [1 2 3 4 5]
Max value: 5
Min value: 1
Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Index of max value: 4


In [8]:
import numpy as np
n1=np.full((5,5),10)
n1

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [12]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 15])

In [19]:
import numpy as np
n1=np.array([34,56,22,34,54])
n2=np.array([21,11,67,90])
print(np.concatenate((n1,n2)))

[34 56 22 34 54 21 11 67 90]


In [20]:
import numpy as np

# Define the start, end, and number of values
start = 1
end = 10
num_values = 5

# Generate an array of evenly spaced values
result = np.linspace(start, end, num_values)

print(result)


[ 1.    3.25  5.5   7.75 10.  ]
